#!/bin/sh
set -eu

LIB=${1-.libs/libmesagbm.so}

if ! [ -f "$LIB" ]
then
  exit 1
fi

FUNCS=$($NM -D --defined-only $LIB | grep -o "T .*" | cut -c 3- | while read func; do
( grep -q "^$func$" || echo $func )  <<EOF
mesa_gbm_device_get_fd
mesa_gbm_device_get_backend_name
mesa_gbm_device_is_format_supported
mesa_gbm_device_destroy
mesa_gbm_device_get_format_modifier_plane_count
mesa_gbm_create_device
mesa_gbm_bo_create
mesa_gbm_bo_create_with_modifiers
mesa_gbm_bo_import
mesa_gbm_bo_map
mesa_gbm_bo_unmap
mesa_gbm_bo_get_width
mesa_gbm_bo_get_height
mesa_gbm_bo_get_stride
mesa_gbm_bo_get_stride_for_plane
mesa_gbm_bo_get_format
mesa_gbm_bo_get_bpp
mesa_gbm_bo_get_offset
mesa_gbm_bo_get_device
mesa_gbm_bo_get_handle
mesa_gbm_bo_get_fd
mesa_gbm_bo_get_plane_count
mesa_gbm_bo_get_handle_for_plane
mesa_gbm_bo_get_modifier
mesa_gbm_bo_write
mesa_gbm_bo_set_user_data
mesa_gbm_bo_get_user_data
mesa_gbm_bo_destroy
mesa_gbm_surface_create
mesa_gbm_surface_create_with_modifiers
mesa_gbm_surface_lock_front_buffer
mesa_gbm_surface_release_buffer
mesa_gbm_surface_has_free_buffers
mesa_gbm_surface_destroy
_fini
_init
EOF
done)

test ! -n "$FUNCS" || echo $FUNCS
test ! -n "$FUNCS"
